spring:
  freemarker:
    suffix: .ftl
  datasource:
    url: jdbc:mysql://localhost:3306/b?serverTimezone=UTC
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置前端页面不进controller直接跳转
  resources:
    static-locations: classpath:/static/, classpath:/templates/
    #配置mybatis-plus控制台打印sql语句
    #mybatis-plus:
    #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #是否开启自动驼峰命名规则（camel case）映射
    #map-underscore-to-camel-case: true
